<?php return function ($fontDir, $rootDir) {
return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'poppins' => array(
    '100_italic' => $fontDir . '/poppins_100_italic_4f5b2e9ee79253dbe021c64d7750cf8b',
    '200_italic' => $fontDir . '/poppins_200_italic_b783ac4b79e16cfc5327e76c79b5f23d',
    '300_italic' => $fontDir . '/poppins_300_italic_3d8565a05ff94d5d2b82277bbd7ebf09',
    'italic' => $fontDir . '/poppins_italic_8e519e1cd8995931e6b5447247f375f3',
    '500_italic' => $fontDir . '/poppins_500_italic_dbc1d05fdcb2e525d3b7bf59ea8e348b',
    '600_italic' => $fontDir . '/poppins_600_italic_8cf665432d4a9aaeac4cc5ce36521613',
    'bold_italic' => $fontDir . '/poppins_bold_italic_89b1cde9b84ed81fef9dbbe6fa9405aa',
    '800_italic' => $fontDir . '/poppins_800_italic_9c2bea87c3e399f4527f575ac7034380',
    '900_italic' => $fontDir . '/poppins_900_italic_8251479c5063296fe468f2fd3fab720e',
    '100' => $fontDir . '/poppins_100_b2651681a0842283ec201b4c2a5b8e23',
    '200' => $fontDir . '/poppins_200_6c0e5484df1387bb3c073297a065f0e6',
    '300' => $fontDir . '/poppins_300_55b40d7af922186cb789c506bd030057',
    'normal' => $fontDir . '/poppins_normal_a7d2460db3514249ea0808da6101365c',
    '500' => $fontDir . '/poppins_500_1321f10338f0e66434dee30474b658c6',
    '600' => $fontDir . '/poppins_600_b9eb07b2d5e0d6ec53e0c7454d6da738',
    'bold' => $fontDir . '/poppins_bold_539ab661c3f4224a64ba7fb9f8385177',
    '800' => $fontDir . '/poppins_800_a738af64a68a81d69351fd2852c747fa',
    '900' => $fontDir . '/poppins_900_9cefc0eae02097ad98f530c2cc1a3051',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome_normal_a07c54af815ea54af1b5e5aa13cc5f8b',
  ),
);
}; ?>